# Site settings
title: Door surveillance system based on Raspberry Pi
SEOTitle: Door surveillance system based on Raspberry Pi
header-img: https://source.unsplash.com/category/nature/2600x500
email: fang.zhoudzt@gmail.com
description: "The blog which recording work process of our project"
keyword: "Door surveillance system, Raspberry Pi"
url: "http://zfdzt.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
#weibo_username:     5092127194
#zhihu_username:
github_username:    zfdzt
#twitter_username:  huxpro
#facebook_username:  huxpro
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  math_engine: mathjax


# Disqus settings
#disqus_username: towdium

# Duoshuo settings
#duoshuo_username: towdium
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-73095900-1'            # Format: UA-xxxxxx-xx
#ga_domain: towdium.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Why not have something fun?"
sidebar-avatar: /img/site/avatar.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



